config/routes.rb
Rails.application.routes.draw do
  resources :responses, only: [:new, :create]
  resources :users, only: [:create]

  root 'responses#new'

end

app/models/response.rb
class Response < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :email, presence: true, uniqueness: true

  after_create :subscribe_user_to_mailing_list
  after_create :send_welcome_email_to_user

  private
    def subscribe_user_to_mailing_list
      SubscribeUserToMailingListJob.perform_later(self)
    end

    def send_welcome_email_to_user
      SendWelcomeEmailJob.perform_later(self)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  def new
    @user = User.new
    @response = Response.new
  end

  def create
    # params[:response][:public_key] = params[:id] if params[:id]
    response = Response.create(responses_params)
    if response.nil?
      redirect_to root_path
    end
    session[:response_id] = response.id
    redirect_to root_path
  end

  private
  def responses_params
    params.require(:response).permit(:location, :age, :tech_interest, :tech_level, :ta_web_app, :ta_mobile_app, :ta_static_web, :ta_search_engine,
                   :ta_online_games, :ta_others, :tp_online_courses, :tp_edu_games, :tp_video_tutorial, :tp_coding_bootcamp, :tp_day_workshop,
                   :tp_other, :ts_expensive, :ts_no_time, :ts_lack_support, :ts_low_priority, :ts_other, :reward_motive, :rt_beauty_fashion,
                   :rt_food, :rt_travel, :rt_edu_scholarship, :rt_job, :rt_other, :wn_dry_and_boring, :wn_too_difficult, :wn_not_a_girl_thing,
                   :wn_just_not_for_me, :public_key)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    user = User.create(users_params)
    redirect_to root_path
  end

  private
  def users_params
     params.require(:user).permit(:public_key, :first_name, :last_name, :email, :location, :response_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

# Status

# Response Value
YES = 1
NO = 0

end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>One Small Step</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/responses/new.html.erb
<div class="container">
	<br>
	<h1 for="LoginForm">Survey Test Page</h1>
	<hr>
	<%= form_for @response do |f| %>
		<table class="table table-hover" >
		<tr>
			<div class="form-group">
				<%= f.label :location, "Location" %>
				<br>
				<%= f.country_select :location, priority_countries: ["MY", "SG"], prompt: "Select a Country" %>
			</div>
		<hr>
		</tr>
		<tr>
			<div class="form-group">
				<%= f.label :age, "Age" %>
				<br>
				<%= f.select :age, [['25', 25], ['26', 26], ['27', 27], ['28', 28], ['29', 29]], class: "form-control" %>
			</div>
			<hr>
		</tr>
		<tr>
			<div class="form-group">
				<%= f.label :tech_interest, "Are you interested in learning more about technology?" %>
				<br>
				<%= f.radio_button :tech_interest, 1, :checked => true %>
				<%= f.label :tech_interest_yes, "Yes" %>
				<%= f.radio_button :tech_interest, 0 %>
				<%= f.label :tech_interest_no, "No" %>
			</div>
			<hr>
		</tr>
		<tr>
			<td>
				<%= f.label "notice", "NOTICE: If you choose YES" %>
			</td>
			<td>
			</td>
			<td>
				<%= f.label "notice", "NOTICE: If you choose NO" %>
			</td>
		</tr>
		<tr>
			<td>
				<div class="form-group">
					<%= f.label :tech_level, "On a scale of 1-10, rate your current understanding of technology?" %>
					<br>
					<%= f.radio_button :tech_level, 1, :checked => true %>
					<%= f.label :tech_level_1, "1" %>
					<%= f.radio_button :tech_level, 2 %>
					<%= f.label :tech_level_2, "2" %>
					<%= f.radio_button :tech_level, 3 %>
					<%= f.label :tech_level_3, "3" %>
					<%= f.radio_button :tech_level, 4 %>
					<%= f.label :tech_level_4, "4" %>
					<%= f.radio_button :tech_level, 5 %>
					<%= f.label :tech_level_5, "5" %>
					<%= f.radio_button :tech_level, 6 %>
					<%= f.label :tech_level_6, "6" %>
					<%= f.radio_button :tech_level, 7 %>
					<%= f.label :tech_level_7, "7" %>
					<%= f.radio_button :tech_level, 8 %>
					<%= f.label :tech_level_8, "8" %>
					<%= f.radio_button :tech_level, 9 %>
					<%= f.label :tech_level_9, "9" %>
					<%= f.radio_button :tech_level, 10 %>
					<%= f.label :tech_level_10, "10" %>
				</div>
			</td>
			<td>
			</td>
			<td>
				<div class="form-group">
					<%= f.label :why_no, "Why not?" %>
					<br>
					<%= f.radio_button :wn_dry_and_boring, 1 %>
					<%= f.label :wn_dry_and_boring, "It's dry and boring" %>
					<%= f.radio_button :wn_too_difficult, 1 %>
					<%= f.label :wn_too_difficult, "It's too difficult" %>
					<%= f.radio_button :wn_not_a_girl_thing, 1 %>
					<%= f.label :wn_not_a_girl_thing, "It's not a girl thing" %>
					<%= f.radio_button :wn_just_not_for_me, 1 %>
					<%= f.label :wn_just_not_for_me, "It's just not for me" %>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<%= f.label "notice", "NOTICE: YES and if your scale is 1-5" %>
			</td>
			<td>
				<%= f.label "notice", "NOTICE: YES and if your scale is 6-10" %>
			</td>
			<td>

			</td>
		</tr>
		<tr>
			<td>
				<div class="form-group">
					<%= f.label :ta_title, "What aspects of technology do you want to learn more about? [Tick all that apply]:" %>
					<br>
					<%= f.check_box :ta_web_app, {class: "myclass"} %>
					<%= f.label :ta_web_app, "Social Media (e.g. Instagram)" %>
					<br>
					<%= f.check_box :ta_mobile_app, {class: "myclass"} %>
					<%= f.label :ta_mobile_app, "Mobile Apps (e.g. Uber)" %>
					<br>
					<%= f.check_box :ta_static_web, {class: "myclass"} %>
					<%= f.label :ta_static_web, "Static Website (e.g. Blog)" %>
					<br>
					<%= f.check_box :ta_search_engine, {class: "myclass"} %>
					<%= f.label :ta_search_engine, "Search Engines (e.g. Google)" %>
					<br>
					<%= f.check_box :ta_online_games, {class: "myclass"} %>
					<%= f.label :ta_online_games, "Online Games (e.g. Candy Crush)" %>
					<br>
					<%= f.label :ta_others, "If others, please specify: " %>
					<br>
					<%= f.text_area :ta_others, {class: "myclass"} %>
					<br>
				</div>
			</td>
			<td>
			</td>
			<td>
			</td>
		</tr>
		<tr>
			<td>
				<div class="form-group">
					<%= f.label :tp_title, "How would you prefer to learn about tech? [Tick all that apply]:" %>
					<br>
					<%= f.check_box :tp_online_courses, {:class => "myclass"} %>
					<%= f.label :tp_online_courses, "Massive Open Online Courses" %>
					<br>
					<%= f.check_box :tp_edu_games, {:class => "myclass"} %>
					<%= f.label :tp_edu_games, "Educational Games" %>
					<br>
					<%= f.check_box :tp_video_tutorial, {:class => "myclass"} %>
					<%= f.label :tp_video_tutorial, "Video Tutorials" %>
					<br>
					<%= f.check_box :tp_coding_bootcamp, {:class => "myclass"} %>
					<%= f.label :tp_coding_bootcamp, "Coding Bootcamps" %>
					<br>
					<%= f.check_box :tp_day_workshop, {:class => "myclass"} %>
					<%= f.label :tp_day_workshop, "Day Workshops" %>
					<br>
					<%= f.label :tp_other, "If others, please specify: " %>
					<br>
					<%= f.text_area :tp_other, {:class => "myclass"} %>
					<br>
				</div>
			</td>
			<td>
				<div class="form-group">
					<%= f.label :tp_title, "How did you get to where you are today? [Tick all that apply]:" %>
					<br>
					<%= f.check_box :tp_online_courses, {:class => "myclass"}, 1 %>
					<%= f.label :tp_online_courses, "Massive Open Online Courses" %>
					<br>
					<%= f.check_box :tp_edu_games, {:class => "myclass"}, 1 %>
					<%= f.label :tp_edu_games, "Educational Games" %>
					<br>
					<%= f.check_box :tp_video_tutorial, {:class => "myclass"}, 1 %>
					<%= f.label :tp_video_tutorial, "Video Tutorials" %>
					<br>
					<%= f.check_box :tp_coding_bootcamp, {:class => "myclass"}, 1 %>
					<%= f.label :tp_coding_bootcamp, "Coding Bootcamps" %>
					<br>
					<%= f.check_box :tp_day_workshop, {:class => "myclass"}, 1 %>
					<%= f.label :tp_day_workshop, "Day Workshops" %>
					<br>
					<%= f.label :tp_other, "If others, please specify: " %>
					<br>
					<%= f.text_area :tp_other, {:class => "myclass"} %>
					<br>
				</div>
			</td>
			<td>
				<div class="form-group">
					<%= f.label :tp_title, "How would you prefer to learn about tech? [Tick all that apply]:" %>
					<br>
					<%= f.check_box :tp_online_courses, {:class => "myclass"}, 1 %>
					<%= f.label :tp_online_courses, "Massive Open Online Courses" %>
					<br>
					<%= f.check_box :tp_edu_games, {:class => "myclass"}, 1 %>
					<%= f.label :tp_edu_games, "Educational Games" %>
					<br>
					<%= f.check_box :tp_video_tutorial, {:class => "myclass"}, 1 %>
					<%= f.label :tp_video_tutorial, "Video Tutorials" %>
					<br>
					<%= f.check_box :tp_coding_bootcamp, {:class => "myclass"}, 1 %>
					<%= f.label :tp_coding_bootcamp, "Coding Bootcamps" %>
					<br>
					<%= f.check_box :tp_day_workshop, {:class => "myclass"}, 1 %>
					<%= f.label :tp_day_workshop, "Day Workshops" %>
					<br>
					<%= f.label :tp_other, "If others, please specify: " %>
					<br>
					<%= f.text_area :tp_other, {:class => "myclass"} %>
					<br>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="form-group">
					<%= f.label :ts_title, "What is stopping you from learning? [Tick all that apply]:" %>
					<br>
					<%= f.check_box :ts_expensive, {:class => "myclass"}, 1 %>
					<%= f.label :ts_expensive, "It's too expensive" %>
					<br>
					<%= f.check_box :ts_no_time, {:class => "myclass"}, 1 %>
					<%= f.label :ts_no_time, "I don't have the time" %>
					<br>
					<%= f.check_box :ts_lack_support, {:class => "myclass"}, 1 %>
					<%= f.label :ts_lack_support, "I lack support" %>
					<br>
					<%= f.check_box :ts_low_priority, {:class => "myclass"}, 1 %>
					<%= f.label :ts_low_priority, "It's just not a priority" %>
					<br>
					<%= f.label :ts_other, "If others, please specify: " %>
					<br>
					<%= f.text_area :ts_other, {:class => "myclass"} %>
					<br>
				</div>
			</td>
			<td>
			</td>
			<td>
				<div class="form-group">
					<%= f.label :ts_title, "What is stopping you from learning? [Tick all that apply]:" %>
					<br>
					<%= f.check_box :ts_expensive, {:class => "myclass"}, 1 %>
					<%= f.label :ts_expensive, "It's too expensive" %>
					<br>
					<%= f.check_box :ts_no_time, {:class => "myclass"}, 1 %>
					<%= f.label :ts_no_time, "I don't have the time" %>
					<br>
					<%= f.check_box :ts_lack_support, {:class => "myclass"}, 1 %>
					<%= f.label :ts_lack_support, "I lack support" %>
					<br>
					<%= f.check_box :ts_low_priority, {:class => "myclass"}, 1 %>
					<%= f.label :ts_low_priority, "It's just not a priority" %>
					<br>
					<%= f.label :ts_other, "If others, please specify: " %>
					<br>
					<%= f.text_area :ts_other, {:class => "myclass"} %>
					<br>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="form-group">
					<%= f.label :reward_motive, "Would real-life rewards (e.g. E-vouchers) motivate you to learn more about tech?:" %>
					<br>
					<%= f.radio_button :reward_motive, 1, :checked => true %>
					<%= f.label :reward_motive_yes, "Yes" %>
					<%= f.radio_button :reward_motive, 0 %>
					<%= f.label :reward_motive_no, "No" %>
					<br>
				</div>
			</td>
			<td>
				<div class="form-group">
					<%= f.label :reward_motive, "Do you think real-life rewards would motivate more women to get into tech?" %>
					<br>
					<%= f.radio_button :reward_motive, 1, :checked => true %>
					<%= f.label :reward_motive_yes, "Yes" %>
					<%= f.radio_button :reward_motive, 0 %>
					<%= f.label :reward_motive_no, "No" %>
					<br>
				</div>
			</td>
			<td>
				<div class="form-group">
					<%= f.label :reward_motive, "Would real-life rewards (e.g. E-vouchers) motivate you to learn more about tech?:" %>
					<br>
					<%= f.radio_button :reward_motive, 1, :checked => true %>
					<%= f.label :reward_motive_yes, "Yes" %>
					<%= f.radio_button :reward_motive, 0 %>
					<%= f.label :reward_motive_no, "No" %>
					<br>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="form-group">
					<%= f.label :reward_types, "What kind of real-life rewards would you prefer?" %>
					<br>
					<%= f.check_box :rt_beauty_fashion, {:class => "myclass"}, 1 %>
					<%= f.label :rt_beauty_fashion, "Beauty / Fashion" %>
					<br>
					<%= f.check_box :rt_food, {:class => "myclass"}, 1 %>
					<%= f.label :rt_food, "Food" %>
					<br>
					<%= f.check_box :rt_travel, {:class => "myclass"}, 1 %>
					<%= f.label :rt_travel, "Travel" %>
					<br>
					<%= f.check_box :rt_edu_scholarship, {:class => "myclass"}, 1 %>
					<%= f.label :rt_edu_scholarship, "Education / Scholarship" %>
					<br>
					<%= f.check_box :rt_job, {:class => "myclass"}, 1 %>
					<%= f.label :rt_job, "Job Opportunities" %>
					<br>
					<%= f.label :rt_other, "If others, please specify: " %>
					<br>
					<%= f.text_area :rt_other, {:class => "myclass"} %>
					<br>
				</div>
			</td>
			<td>
			</td>
			<td>
				<div class="form-group">
					<%= f.label :reward_types, "What kind of real-life rewards would you prefer?" %>
					<br>
					<%= f.check_box :rt_beauty_fashion, {:class => "myclass"}, 1 %>
					<%= f.label :rt_beauty_fashion, "Beauty / Fashion" %>
					<br>
					<%= f.check_box :rt_food, {:class => "myclass"}, 1 %>
					<%= f.label :rt_food, "Food" %>
					<br>
					<%= f.check_box :rt_travel, {:class => "myclass"}, 1 %>
					<%= f.label :rt_travel, "Travel" %>
					<br>
					<%= f.check_box :rt_edu_scholarship, {:class => "myclass"}, 1 %>
					<%= f.label :rt_edu_scholarship, "Education / Scholarship" %>
					<br>
					<%= f.check_box :rt_job, {:class => "myclass"}, 1 %>
					<%= f.label :rt_job, "Job Opportunities" %>
					<br>
					<%= f.label :rt_other, "If others, please specify: " %>
					<br>
					<%= f.text_area :rt_other, {:class => "myclass"} %>
					<br>
				</div>
			</td>
		</tr>
		</table>
		<%= f.hidden_field :public_key, {value: params[:id]} %>
		<%= f.submit "Submit", class: "btn btn-primary" %>
	<% end %>
	<hr>
</div>
<br>

<div class="container">
	<h1> User Form in same page </h1>
	<hr>
	<%= form_for @user, url: users_path do |f| %>
		<div class="form-group">
			<%= f.label :first_name, "First Name:" %>
			<%= f.text_field :first_name, {class: "form-control", required: true} %>
			<br>
			<%= f.label :last_name, "Last Name:" %>
			<%= f.text_field :last_name, {class: "form-control", required: true} %>
			<br>
			<%= f.label :email, "Email:" %>
			<%= f.email_field :email, {class: "form-control", required: true} %>
			<br>
			<%= f.label :location, "Country:" %>
			<%= f.text_field :location, {class: "form-control", required: true} %>
			<br>
			<%= f.label :response_id, "respond_id (debugging only. You should reterive from session[:response_id]):" %>
			<%= f.text_field :response_id, {class: "form-control"} %>
			<br>
			<br>
		</div>
		<%= f.submit "Submit", class: "btn btn-primary" %>
	<% end %>
</div>